### PR TITLE
Added btn-filled, updated the README and index.html

### PR DESCRIPTION
**Pull request by Frewacom**
**What is the purpose of this pull request?**
Added a new type of button

**How is this achieved?**
By styling a new class called "filled" in the _button.scss file.
The class is used directly after the main button class like this:
```html
<button type="button" name="button" class="button filled">Default</button>
```

**Which issue number does this fix?**
#4

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Thanks for the pull request, but this new button doesn’t currently follow the current standard for class names. 

You currently have the class name btn-filled, where as it should be “filled” to follow the current class name standard. Make this change and it will be ready to be merged. Thanks and Happy coding!

**Comment by Frewacom** [comment]
Will do.

**Comment by Frewacom** [comment]
Update the name to follow your naming convention and made sure to run npm run prod before pushing.

**Comment by cpdevelops** [comment]
Thank you for the PR. I hope you continue to contribute to simple.css. Merging now.

**Pull request merged**
