### PR TITLE
feat(forms): added forms and some documentation

### PR DESCRIPTION
**Pull request by jberry93**
**What is the purpose of this pull request?**
Add forms

**How is this achieved?**
Created a SASS file and HTML markup in the index.html

**Which issue number does this fix?**
#78

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by jberry93** [comment]
**Preview**

## Login example:

forms1

## General controls:

forms2

## Sizes and readonly:

forms3

## Inline, checkboxes, and radios:

forms4

**Comment by cpdevelops** [comment]
Hey there! Thanks for the contribution. Could you please also add documentation detailing the new feature? You can find the source for the documentation in the ```docs``` folder.

**Comment by jberry93** [comment]
Hey @cpdevelops! I added documentation detailing the new feature in the first commit. Go to `Files changed`, click on the `Jump to...` dropdown to view all file changes and `Forms.md` should be the 3rd option. Let me know if you want me to revise it or make any improvements. Thanks for the quick response 👍

**Comment by cpdevelops** [comment]
Oh sorry! I didn't realize that you had already added it. Thanks for pointing that out to me.

Looks great and I will go ahead and merge the changes.

**Pull request merged**
