### PR TITLE
package-lock.json might be failing?

### PR DESCRIPTION
**Pull request by dvlden**
**Which issue number does this fix?**
Maybe, #65? I don't have any issues when running `npm install`

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by cpdevelops** [comment]
What is the purpose of package-lock.json? I am not sure, but I believe you put it in .gitignore at one point and now it is gone.

**Comment by dvlden** [comment]
Don’t really know. Haven’t done research on that. But apparently, npm insists on uploading such a file to git repo.

**Comment by cpdevelops** [comment]
OK, then. Guess I'll just go ahead and merge this PR and see if that fixes my issue.

**Pull request merged**
