### PR TITLE
table styling

### PR DESCRIPTION
**Pull request by f0x52**
**What is the purpose of this pull request?**
Add basic styling for tables

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by f0x52** [comment]
done

**Comment by cpdevelops** [comment]
Is there any chance that you could provide some screenshots of this new component in action? Unfortunately I am unable to check it out for myself, so screenshots would be very helpful for getting this PR merged quicker. Thanks.

**Comment by f0x52** [comment]
[screenshot](https://w1r3.net/dYPTSF.png)

**Comment by cpdevelops** [comment]
I don't seem to be able to open the link for some reason. I am on a private company network, so that might be an issue. Is there any chance you could re-upload the image here: https://imgbb.com/?

**Comment by f0x52** [comment]
here you go: https://ibb.co/iwgKbR

**Comment by cpdevelops** [comment]
Thanks so much! It looks great and I will go ahead and merge.

**Pull request merged**
