### PR TITLE
Refactoring...

### PR DESCRIPTION
**Pull request by dvlden**
**What is the purpose of this pull request?**
- There were some minor refactoring as well as one major issue with variables. It was missing `!default` at the end of each variable. This is a must for any open source package... Here's a quick [reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Variable_Defaults___default).

- Added `npm-debug.log` to `.gitignore`

- Prettified keywords in `package.json`

- Compiled once again due to some new contributions

### CODE REVIEW

**Comment by dvlden** [comment]
Waiting for merge before continuing with Alert Component implementation.
I'm guessing that day is tomorrow. Is there a chance you can make me collaborator so that I can manage those pull requests too?

**Comment by cpdevelops** [comment]
Sorry about the wait on the merge. I will hopefully be able to merge within the next few hours, but unfortunately I am busy at the moment. 

The only issue I have with adding you as a contributor is issues with you having push permission to master, but if you could make sure to keep your changes to a separate branch then it will be fine. I am liking your reviews on PRs and issues and I think it would be great if you were a full contributor. 

What time zone are you in so that we can coordinate easier for issues such as PR merging

**Comment by cpdevelops** [comment]
Sorry about the wait. I will merge this PR now. But still please respond to my previous comments:

> What time zone are you in so that we can coordinate easier for issues such as PR merging

> The only issue I have with adding you as a contributor is issues with you having push permission to master, but if you could make sure to keep your changes to a separate branch then it will be fine. I am liking your reviews on PRs and issues and I think it would be great if you were a full contributor.

**Comment by dvlden** [comment]
Now I am starting to think that we're into the same or similar time zone. **GMT+2**
Separate branch sounds good, but if we're into same or similar time zone, we might do okay as is.

Sometimes I just stay up late...

**Pull request merged**
