### PR TITLE
refactoring and minor updates...

### PR DESCRIPTION
**Pull request by dvlden**
**What is the purpose of this pull request?**
- alert component is now updated and supports closing with animation
- html file is updated and contains fixes for multiple issue references
- readme file updated to take effect of new formatting
- now includes latest normalize from node modules
- gulp tasks have been improved and now support script compiling
- modular structure possible, but not being used for now
- source structure changed a bit
- code block absolute positioned text now fixed to be within its container, even tho this component is still so bad
- minor spacing polish and alignment of previous contributors
- precommit command from package.json now includes all into git add, not just `dist/simple.css`

**Which issue number does this fix?**
#52 #53 #30 #40 

P.S. Sorry @soumam007, I just found it easier to throw in this logo improvements and improve it even more in single pull request so that it does not clash this big update with smaller pull requests.

### CODE REVIEW

**Comment by soumam007** [comment]
please show us the **screenshots** of what new changes you have made and what i think since within one PR  you are changing such huge amount of code we should talk in the gitter channel first. @dvlden 
 because its difficult for one to understand if such chunks of code are injected at once

**Comment by dvlden** [comment]
@soumam007 - Isn't it already easy enough looking at file changes?
https://github.com/cpdevelops/simple.css/pull/54/files

Most of the code is compiled css, js, minified version and new gulp task.

**Comment by cpdevelops** [comment]
Looks like I merged @soumam007's PR fixing logo issues without noticing that this PR does the same. Can you try and quickly fix the logo merge issues and then I will gladly merge the PR

**Comment by soumam007** [comment]
ok so now what is to be done ?
I havent faced such issues before

**Comment by dvlden** [comment]
I'll resolve this, gimme a sec.

**Comment by soumam007** [comment]
please tell me what do we do when there is a merge conflict.
Where the changes should me made @dvlden ?
That will be a good topic for me to learn as a new comer :)

**Comment by dvlden** [comment]
Well, I am not an Git pro, just know some basics... So this is the approach I take before I want to make a pull request.

I fork the repo and never delete the fork. If some updates come `git pull` won't work as it'd try to fetch changes from your own repo that you forked. So I follow this:
[Configuring a remote for a fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
[Syncing a fork](https://help.github.com/articles/syncing-a-fork/)

I configure it obviously for the first time only and every time before I want to make any changes I follow `syncing a fork` steps.

After that, I check for current pull requests and I try not to modify any files where it'd have conflicts (e.g., if index.html was modified already, I wouldn't touch it until pull request is merged to master branch; when it is, I'd sync a fork and do changes...)

In this case, there was a conflict as @cpdevelops did not see that #54 fixes most and some more and that current pull requests should be closed without a merge, hence conflict appeared as you changed `index.html` and I did too... Github shows this to the one who made `pull request` in this case (me) and you can click the button and hunt the problems. Remove either my changes or your changes or leave both if it that was the correct case. Mark as resolved and it becomes green. I know that we can fix issues via terminal commands in our favorite code editors, but I am not familiar how.

Well, hopefully i was a bit helpful here 👍

**Pull request merged**
