### PR TITLE
added various types of list in simple.css

### PR DESCRIPTION
**Pull request by soumam007**
**What is the purpose of this pull request?**
To add the list feature

**How is this achieved?**
by adding components to index.html and simple.css

**Which issue number does this fix?**
#4 

**Preview**
screenshot from 2017-10-14 20-43-25

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by soumam007** [comment]
@cpdevelops  can you give me the link of CONTRIBTING.md?
and did i do anything wrong in the procedure?

**Comment by soumam007** [comment]
yes @cpdevelops I am done with it.
Only one step was left
      npm run dev && npm run watch
that too completed, i guess now you can merge it :)


@dvlden  please give a review

**Comment by soumam007** [comment]
thanks @cpdevelops  , by the way one question ?
how did you know I had some leftovers , or did you say it as formality?

**Pull request merged**
