### PR TITLE
logo not found in index.html  fixed #51

### LINKED ISSUE #51: logo.svg not detected in index.html
do you want to work on it ?
**yes**

Preview:-

screenshot from 2017-10-05 13-13-18

### PR DESCRIPTION
**Pull request by soumam007**
**What is the purpose of this pull request?**
To make the logo.svg visible in the website

**How is this achieved?**
changing logo.png to logo.svg

**Which issue number does this fix?**
#51

### CODE REVIEW

**Comment by dvlden** [comment]
You could fix #53 too... Just imagine having a `.jpg` with fairly large size, even tho `.svg` is different, but imagine it that way.

So simply add some width to it, the percentage might be just fine too.

`Simple.css Logo

**Comment by soumam007** [comment]
Ok thanks @dvlden once @cpdevelops merges it I will make the necessary changes

**Comment by dvlden** [comment]
#54 fixes this and more

**Comment by cpdevelops** [comment]
Thank you for fixing this issue. I did not notice this.

Merging now.

**Pull request merged**
