### PR TITLE
Add basic grid classes

### PR DESCRIPTION
**Pull request by lpraz**
Resolves issue #31 by adding a row class and two sets of column classes (divided into twelfths). One (`column-large-*`) collapses to a vertical layout if the screen is small enough, the other (`column-small-*`) doesn't.

This probably isn't ready to merge yet, as I'm still having some issues getting npm to build the repository (with `npm run dev && npm run watch`) correctly. Can anyone help with this?

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by cpdevelops** [comment]
There are many merge conflicts with this PR. You can hit resolve conflicts and fix those in your repository, and they will go into this current PR.

> This probably isn't ready to merge yet, as I'm still having some issues getting npm to build the repository (with npm run dev && npm run watch) correctly. Can anyone help with this?

Have you made sure to install all the dependencies? If you have, also try running ``` npm run prod ``` which will build for production and see if that fixes your issue.

**Comment by lpraz** [comment]
I've tried to `npm install` as root while in the project directory, which works fine. However, both `npm run dev` and `npm run prod` throw an error with a stack trace from gulp that says "no such file or directory, scandir '<the project directory>/node_modules/node-sass/vendor' ".

**Comment by lpraz** [comment]
Disregard the above, it turns out it was an error with permissions on my part. `npm install` shouldn't be run as root, or else something in the build process won't have access to whatever it needs.

**Comment by lpraz** [comment]
I don't think `calc` can be entirely eliminated due to the browser needing to mix pixels and percentages to calculate column widths (unless padding also becomes percentage-based), but everything else works just fine (implemented in fda71d5).

**Comment by dvlden** [comment]
It's fine, I'll let @cpdevelops decide if it works out for him. It's good starting point at least.
You can remove `calc()` and this would be your basic formula that you'd loop through your `grid generator` mixin.

```sass
@function grid-calc ($number, $columns: $dfr-grid-columns) {
    @return (100 / $columns * $number) + %;
}
```

Of course, you'd need to rewrite everything and build a more complex grid that outputs simple results, but as @cpdevelops said, when you asked, it can be the simplest grid, for now, so I'm okay with your PR.

**Comment by cpdevelops** [comment]
Looks ok for now. If there are any issues with it they can be edited in the future. Merging now.

Thanks for the contribution.

**Pull request merged**
