### PR TITLE
Navfoo

### PR DESCRIPTION
**Pull request by soumam007**
**What is the purpose of this pull request?**
Purpose of the pull request is to add a navigation bar and a footer for the websit like bootstrap

**How is this achieved?**
By using html and css/scss

**Which issue number does this fix?**
#4 

**Preview**
Check Navbar
screenshot from 2017-10-19 19-26-12

Made fixed and transparent when scrolling down
screenshot from 2017-10-19 19-26-23

check footer
screenshot from 2017-10-19 19-26-31

written instead of placeholder
screenshot from 2017-10-19 19-26-48

### CODE REVIEW

**Comment by cpdevelops** [comment]
Hey there! Before continuing with this pull request, please make sure you have read through the README and CONTRIBUTING files, and have added your changes to the demo site at index.html.

**Comment by soumam007** [comment]
yeah everything done except writing the docs, i will be doing it shortly

**Comment by soumam007** [comment]
@cpdevelops you there?

**Comment by cpdevelops** [comment]
Sorry @soumam007 . Been a little busy lately, so I haven't been able to do code review. 

Let me review this now and get back to you.

**Comment by cpdevelops** [comment]
- Logo seems to be above the rest of the navbar. Everything should be on the same level.
- Navbar opacity is too low, should be a solid object pushing the rest of the site down instead of something over the rest of the site with the site still visible.
- "project maintainer" section of footer does not need to be there.
- "FB" and "Gitter" should be capitalized.
- Facebook link should not be there, since we do not have a Facebook page for the application.

Once these changes are fixed, the pull request will be able to be merged. You can keep this PR open and as you add changes to your fork of the repo, the commits will be added here.

If you would like, you can add me as a contributor to your fork of the framework and I would be happy to help you out with these changes when I get the chance.

**Comment by soumam007** [comment]
Ok @cpdevelops , I want to add you but can you tell me how to do that because in right hand side I already see something ""allow edits from maintainers"" so I guess you are allowed to make changes :)

**Comment by cpdevelops** [comment]
It does not seem that I am able to make changes to your fork. You can go to your fork of the project, go to settings, Contributors (it might be called Collaborators, I am not sure), and then add my username. Once you add my username, I will receive an invitation to be able to make changes to your fork.

**Comment by cpdevelops** [comment]
@soumam007 are you still working on this project?

**Comment by cpdevelops** [comment]
@soumam007 are you still working on this project?

**Pull request closed without merging**
